MODEL:
  TYPE: refine_res
  SIZE: '1024'
  REFINE: True
  CONV_BODY: refine_res.RefineResnet18
  NUM_CLASSES: 81
  LOAD_PRETRAINED_WEIGHTS: False
  PRETRAIN_WEIGHTS: None

TRAIN:
  OVERLAP: 0.5
  BGR_MEAN: [104, 117, 123]
  BATCH_SIZE: 5
  OHEM: True
  NEG_RATIO: 3
  WARMUP: True
  WARMUP_EPOCH: 2
  TRAIN_ON: True


SMALL:
  FEATURE_MAPS: [[40, 40], [20, 20], [10, 10], [5, 5]]
  ARM_CHANNELS: [64, 128, 256, 64]
  ODM_CHANNELS: [128, 128, 128, 128]
  NUM_ANCHORS: [3, 3, 3, 3]
  STEPS: [[8, 8], [16, 16], [32, 32], [64, 64]]
  MIN_SIZES: [30, 64, 128, 256]
  MAX_SIZES: [64, 128, 256, 315]
  ASPECT_RATIOS : [[2, 0.5], [2, 0.5], [2, 0.5], [2, 0.5]]
  VARIANCE : [0.1, 0.2]
  CLIP: True
  IMG_WH: [320, 320]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: False

BIG:
  FEATURE_MAPS: [[64, 64], [32, 32], [16, 16], [8, 8]]
  ARM_CHANNELS: [64, 128, 256, 64]
  ODM_CHANNELS: [128, 128, 128, 128]
  NUM_ANCHORS: [3, 3, 3, 3]
  STEPS: [[16, 16], [32, 32], [64, 64], [128, 128]]
  MIN_SIZES: [32, 64, 128, 256]
  MAX_SIZES: [128, 256, 512, 768]
  ASPECT_RATIOS : [[2, 0.5], [2, 0.5], [2, 0.5], [2, 0.5]]
  CLIP: True
  IMG_WH: [1024, 1024]
  INPUT_FIXED: True # if you want to input different size, you need to set this False.
  USE_MAX_SIZE: False

SOLVER:
  WEIGHT_DECAY: 0.0005
  BASE_LR: 0.001
  GAMMA: 0.1
  MOMENTUM: 0.9
  EPOCH_STEPS: [0, 150, 200]  
  END_EPOCH: 250
  START_EPOCH: 0

DATASETS:
  TRAIN_TYPE: [['2017', 'train']]
  VAL_TYPE: [['2017', 'val']]
  DATAROOT: '/home/wjltroy/Data/COCO2017'
  DATA_TYPE: 'COCO'
  SETS:
    VOC: [['0712', '0712_trainval']]
    VOC0712PLUS: [['0712', '0712_trainval_test']]
    VOC0712: [['2012', '2012_trainval']]
    COCO: [['2017', 'train']]
    VOC2007: [['0712', "2007_test"]]
    COCOval: [['2017', 'val']]
    VOCROOT: 'data/datasets/VOCdevkit0712/'
    COCOROOT: '/home/wjltroy/Data/COCO2017'
  
TEST:
  INPUT_WH: [1024, 1024]
  CONFIDENCE_THRESH: 0.01
  NMS_OVERLAP: 0.45
  BATCH_SIZE: 1
  




